### ISSUE TITLE
ERROR in npm install 

### ISSUE THREAD

**Issue by edwinhuish** [devjin0617/vue2-admin-lte#38]
ERROR in ``` npm install ```

```
npm ERR! code EINTEGRITY
npm ERR! sha1-+TA2VtlWyNbIVuSUIWfg3sl/p6g= integrity checksum failed when using sha1: wanted sha1-+TA2VtlWyNbIVuSUIWfg3sl/p6g= but got sha1-wfP0vRAlVRCweobrlcTI0PcyuwM=. (1176974 bytes)
npm ERR! Cannot read property 'write' of null
```

**Comment by devjin0617** [comment]
what is npm version?

**Comment by edwinhuish** [comment]
virtualbox Ubuntu 17.04
node v8.0.0
npm 5.0.3

**Comment by edwinhuish** [comment]
virtualbox Ubuntu 17.04
node v8.0.0
npm 5.0.3

**Comment by devjin0617** [comment]
it's maybe npm issue
https://github.com/npm/npm/issues/16861

`npm cache clean --force` or `npm i -g npm`

**Comment by edwinhuish** [comment]
I had try the 2 ways, but get the same problem, (another project dosen't have this problem)
```
edwin@edwin-VirtualBox:/media/sf_www/vue2-admin-lte$ sudo npm i -g npm
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
+ npm@5.0.3
updated 1 package in 16.931s

edwin@edwin-VirtualBox:/media/sf_www/vue2-admin-lte$ npm install --no-bin-links
npm ERR! Cannot read property 'write' of null
npm WARN karma-sinon-chai@1.3.1 requires a peer of sinon@^2.1.0 but none was installed.
npm WARN vue2-admin-lte@0.4.2 No license field.
npm WARN vue2-admin-lte@0.4.2 hompage should probably be homepage.

npm ERR! code EINTEGRITY
npm ERR! sha1-2lbc001C6e8a82K+FVIKBTqdQ9s= integrity checksum failed when using sha1: wanted sha1-2lbc001C6e8a82K+FVIKBTqdQ9s= but got sha1-s/go3vdQW2dHPCbDYTJWb5jjt0M=. (242786 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/edwin/.npm/_logs/2017-06-11T16_25_11_791Z-debug.log
```
```
edwin@edwin-VirtualBox:/media/sf_www/vue2-admin-lte$ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
edwin@edwin-VirtualBox:/media/sf_www/vue2-admin-lte$ npm install --no-bin-links
npm WARN karma-sinon-chai@1.3.1 requires a peer of sinon@^2.1.0 but none was installed.
npm WARN vue2-admin-lte@0.4.2 No license field.
npm WARN vue2-admin-lte@0.4.2 hompage should probably be homepage.

npm ERR! code EINTEGRITY
npm ERR! sha1-2lbc001C6e8a82K+FVIKBTqdQ9s= integrity checksum failed when using sha1: wanted sha1-2lbc001C6e8a82K+FVIKBTqdQ9s= but got sha1-kXvrSr99uxpUKw1RZOx7MNWvONs=. (260870 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/edwin/.npm/_logs/2017-06-11T16_33_44_533Z-debug.log
```

**Comment by devjin0617** [comment]
can you give me a error log file?

`/home/edwin/.npm/_logs/2017-06-11T16_33_44_533Z-debug.log`

**Comment by edwinhuish** [comment]
It's more than 9000 rows logs, I copy some latest code to you, I think it's enough.
```
17307 silly pacote trying ms@http://registry.npm.taobao.org/ms/download/ms-0.7.2.tgz by hash: sha1-riXPJRKziFodldfwN4aNhDESR2U=
17308 silly pacote data for sha1-QMRT5n5uE8kB3ewxeviYbNqe/4w= not present. Using manifest.
17309 silly pacote data for sha1-riXPJRKziFodldfwN4aNhDESR2U= not present. Using manifest.
17310 silly pacote stream-combiner@http://registry.npm.taobao.org/stream-combiner/download/stream-combiner-0.0.4.tgz extracted in 5559ms
17311 silly extract socket.io-adapter@0.5.0
17312 silly pacote trying socket.io-adapter@http://registry.npm.taobao.org/socket.io-adapter/download/socket.io-adapter-0.5.0.tgz by hash: sha1-y21LuL7IHhB4uZZ3+c7QBGBmu4s=
17313 silly pacote data for sha1-y21LuL7IHhB4uZZ3+c7QBGBmu4s= not present. Using manifest.
17314 silly pacote statuses@http://registry.npm.taobao.org/statuses/download/statuses-1.3.1.tgz extracted in 4933ms
17315 silly extract socket.io-parser@2.3.1
17316 silly pacote trying socket.io-parser@http://registry.npm.taobao.org/socket.io-parser/download/socket.io-parser-2.3.1.tgz by hash: sha1-3VMgJRA85Clpcya+/WQAX8/ltKA=
17317 silly pacote data for sha1-3VMgJRA85Clpcya+/WQAX8/ltKA= not present. Using manifest.
17318 silly pacote babel-traverse@http://registry.npm.taobao.org/babel-traverse/download/babel-traverse-6.25.0.tgz extracted in 21679ms
17319 silly extract debug@2.2.0
17320 silly pacote trying debug@http://registry.npm.taobao.org/debug/download/debug-2.2.0.tgz by hash: sha1-+HBX6ZWxofauaklgZkE3vFbwOdo=
17321 silly pacote data for sha1-+HBX6ZWxofauaklgZkE3vFbwOdo= not present. Using manifest.
17322 silly pacote alter@http://registry.npm.taobao.org/alter/download/alter-0.2.0.tgz extracted in 4093ms
17323 http fetch GET 200 http://registry.npm.taobao.org/socks-proxy-agent/download/socks-proxy-agent-2.1.0.tgz 1538ms
17324 http fetch GET 200 http://registry.npm.taobao.org/socks/download/socks-1.1.10.tgz 1488ms
17325 http fetch GET 200 http://registry.npm.taobao.org/clean-css/download/clean-css-4.1.3.tgz 1956ms
17326 http fetch GET 200 http://registry.npm.taobao.org/source-list-map/download/source-list-map-0.1.8.tgz 1728ms
17327 http fetch GET 200 http://registry.npm.taobao.org/sort-keys/download/sort-keys-1.1.2.tgz 1671ms
17328 silly extract ms@0.7.1
17329 silly pacote trying ms@http://registry.npm.taobao.org/ms/download/ms-0.7.1.tgz by hash: sha1-nNE8A62/8ltl7/3nzoZO6VIBcJg=
17330 silly pacote data for sha1-nNE8A62/8ltl7/3nzoZO6VIBcJg= not present. Using manifest.
17331 silly pacote assert-plus@http://registry.npm.taobao.org/assert-plus/download/assert-plus-1.0.0.tgz extracted in 4285ms
17332 http fetch GET 200 http://registry.npm.taobao.org/object-assign/download/object-assign-4.1.0.tgz 1605ms
17333 silly pacote spdx-correct@http://registry.npm.taobao.org/spdx-correct/download/spdx-correct-1.0.2.tgz extracted in 3485ms
17334 silly pacote spdx-license-ids@http://registry.npm.taobao.org/spdx-license-ids/download/spdx-license-ids-1.2.2.tgz extracted in 3497ms
17335 silly extract isarray@0.0.1
17336 silly pacote trying isarray@http://registry.npm.taobao.org/isarray/download/isarray-0.0.1.tgz by hash: sha1-ihis/Kmo9Bd+Cav8YDiTmwXR7t8=
17337 silly extract debug@2.3.3
17338 silly pacote trying debug@http://registry.npm.taobao.org/debug/download/debug-2.3.3.tgz by hash: sha1-QMRT5n5uE8kB3ewxeviYbNqe/4w=
17339 http fetch GET 200 http://registry.npm.taobao.org/debug/download/debug-2.3.3.tgz 1710ms
17340 http fetch GET 200 http://registry.npm.taobao.org/ms/download/ms-0.7.2.tgz 1627ms
17341 silly extract ms@0.7.2
17342 silly pacote trying ms@http://registry.npm.taobao.org/ms/download/ms-0.7.2.tgz by hash: sha1-riXPJRKziFodldfwN4aNhDESR2U=
17343 silly pacote data for sha1-ihis/Kmo9Bd+Cav8YDiTmwXR7t8= not present. Using manifest.
17344 http fetch GET 200 http://registry.npm.taobao.org/postcss/download/postcss-6.0.1.tgz 18402ms
17345 http fetch GET 200 http://registry.npm.taobao.org/socket.io-adapter/download/socket.io-adapter-0.5.0.tgz 1576ms
17346 http fetch GET 200 http://registry.npm.taobao.org/postcss/download/postcss-6.0.1.tgz 18491ms
17347 http fetch GET 200 http://registry.npm.taobao.org/socket.io-parser/download/socket.io-parser-2.3.1.tgz 1950ms
17348 http fetch GET 200 http://registry.npm.taobao.org/debug/download/debug-2.2.0.tgz 2125ms
17349 http fetch GET 200 http://registry.npm.taobao.org/postcss/download/postcss-6.0.1.tgz 20150ms
17350 verbose unlock done using /home/edwin/.npm/_locks/staging-063a5690e8c40c75.lock for /media/sf_www/vue2-admin-lte/node_modules/.staging
17351 warn karma-sinon-chai@1.3.1 requires a peer of sinon@^2.1.0 but none was installed.
17352 warn vue2-admin-lte@0.4.2 No license field.
17353 warn vue2-admin-lte@0.4.2 hompage should probably be homepage.
17354 verbose stack Error: sha1-2lbc001C6e8a82K+FVIKBTqdQ9s= integrity checksum failed when using sha1: wanted sha1-2lbc001C6e8a82K+FVIKBTqdQ9s= but got sha1-kXvrSr99uxpUKw1RZOx7MNWvONs=. (260870 bytes)
17354 verbose stack     at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:278:19)
17354 verbose stack     at emitNone (events.js:110:20)
17354 verbose stack     at Transform.emit (events.js:207:7)
17354 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
17354 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
17354 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
17355 verbose cwd /media/sf_www/vue2-admin-lte
17356 verbose Linux 4.10.0-22-generic
17357 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
17358 verbose node v8.0.0
17359 verbose npm  v5.0.3
17360 error code EINTEGRITY
17361 error sha1-2lbc001C6e8a82K+FVIKBTqdQ9s= integrity checksum failed when using sha1: wanted sha1-2lbc001C6e8a82K+FVIKBTqdQ9s= but got sha1-kXvrSr99uxpUKw1RZOx7MNWvONs=. (260870 bytes)
17362 verbose exit [ 1, true ]
```


### And, I think the problem is this: ###
```
17352 warn vue2-admin-lte@0.4.2 No license field.
17353 warn vue2-admin-lte@0.4.2 hompage should probably be homepage.
```

**Comment by devjin0617** [comment]
are you using a proxy server in npm?
because, i saw `http://registry.npm.taobao.org` in the log

**Comment by edwinhuish** [comment]
yes, it's a mirror in China. It's always fine..... I will try with the official source, and tell you later.

**Comment by edwinhuish** [comment]
Now... I got another ERROR:

```
3557 silly resolveWithNewModule is-obj@1.0.1 checking installable status
3558 silly pacote range manifest for slide@^1.1.5 fetched in 1ms
3559 silly resolveWithNewModule slide@1.1.6 checking installable status
3560 silly pacote range manifest for package-json@^2.0.0 fetched in 4ms
3561 silly resolveWithNewModule package-json@2.4.0 checking installable status
3562 silly pacote range manifest for registry-auth-token@^3.0.1 fetched in 5ms
3563 silly resolveWithNewModule registry-auth-token@3.3.1 checking installable status
3564 silly pacote range manifest for registry-url@^3.0.3 fetched in 6ms
3565 silly resolveWithNewModule registry-url@3.1.0 checking installable status
3566 http fetch GET 304 https://registry.npmjs.org/got 401ms (from cache)
3567 silly fetchPackageMetaData error for got@^5.0.0 Unexpected end of input at 1:20275
3567 silly fetchPackageMetaData or-class":"^3.0.0","@floatdrop/duplexer2":"^0.1.4","get-stream":"^1.1
3567 silly fetchPackageMetaData                                                                      ^
3568 verbose stack SyntaxError: Unexpected end of input at 1:20275
3568 verbose stack or-class":"^3.0.0","@floatdrop/duplexer2":"^0.1.4","get-stream":"^1.1
3568 verbose stack                                                                      ^
3568 verbose stack     at Object.parseJSON (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
3568 verbose stack     at parse (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/index.js:10:13)
3568 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
3568 verbose stack     at <anonymous>
3568 verbose stack     at process._tickCallback (internal/process/next_tick.js:169:7)
3569 verbose cwd /media/sf_www/vue2-admin-lte
3570 verbose Linux 4.10.0-22-generic
3571 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
3572 verbose node v8.0.0
3573 verbose npm  v5.0.3
3574 error Unexpected end of input at 1:20275
3574 error or-class":"^3.0.0","@floatdrop/duplexer2":"^0.1.4","get-stream":"^1.1
3574 error                                                                      ^
3575 verbose exit [ 1, true ]
```

**Comment by zLegend-210** [comment]
try `npm cache verify` and install again.

**Comment by devjin0617** [comment]
@zLegend-210 wow! thanks!
