### ISSUE TITLE
启动项目报错

### ISSUE THREAD

**Issue by haoyanhong** [devjin0617/vue2-admin-lte#66]
从github上下的代码，老是启动报错，刚开机的时候启动成功的几率会高一点

**Comment by nckf** [comment]
①请贴出你的错误日志
②描述你产生错误的过程
③建议最好用英文描述因为此项目使用者在全球的

**Comment by noeeka** [comment]
ERROR  Failed to compile with 1 errors14:20:12

Module build failed: Error: Cannot find module 'eslint/lib/formatters/stylish'
Require stack:
- D:\Project\Nodejs\vue2-admin-lte\node_modules\eslint-loader\index.js
- D:\Project\Nodejs\vue2-admin-lte\node_modules\loader-runner\lib\loadLoader.js
- D:\Project\Nodejs\vue2-admin-lte\node_modules\loader-runner\lib\LoaderRunner.js
- D:\Project\Nodejs\vue2-admin-lte\node_modules\webpack\lib\NormalModule.js
- D:\Project\Nodejs\vue2-admin-lte\node_modules\webpack\lib\NormalModuleFactory.js
- D:\Project\Nodejs\vue2-admin-lte\node_modules\webpack\lib\Compiler.js
- D:\Project\Nodejs\vue2-admin-lte\node_modules\webpack\lib\webpack.js
- D:\Project\Nodejs\vue2-admin-lte\build\dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.module.exports (D:\Project\Nodejs\vue2-admin-lte\node_modules\eslint-loader\index.js:156:18)

in web browser it showed:
Cannot GET /
